[book]
title = "Shire"
authors = ["Justin Jones"]
language = "en"
src = "src"

[build]
build-dir = "book"

[output.html]
default-theme = "ayu"
preferred-dark-theme = "ayu"
git-repository-url = "https://github.com/justinjdev/shire"
site-url = "https://shire.justinj.dev/"
